In [1]:
import sys

print("Python version:", sys.version)
print("Python path:", sys.executable)
print("FlightSaver AI is ready!")

Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Python path: c:\Users\sanga\OneDrive\Desktop\FlightSaverAI\.venv\Scripts\python.exe
FlightSaver AI is ready!

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
import catboost

print("All libraries are ready!")
print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)
print("CatBoost:", catboost.__version__)

All libraries are ready!
Pandas: 3.1.0
Scikit-learn: 1.9.1
CatBoost: 1.2.10

In [3]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFiles and folders:")
for item in os.listdir():
    print(item)

Current folder:
c:\Users\sanga\OneDrive\Desktop\FlightSaverAI

Files and folders:
.venv
FlightSaverAI.ipynb

In [5]:
import os

for root, dirs, files in os.walk("."):
    dirs[:] = [d for d in dirs if d not in [".venv", ".git", "__pycache__"]]

    for file in files:
        if file.lower().endswith((".csv", ".xlsx", ".xls", ".parquet")):
            print(os.path.join(root, file))

In [7]:
import os

print("Notebook is looking inside:")
print(os.getcwd())

print("\nEverything inside this folder:")
print(os.listdir("."))

Notebook is looking inside:
c:\Users\sanga\OneDrive\Desktop\FlightSaverAI

Everything inside this folder:
['.venv', 'FlightSaverAI.ipynb', 'Flight_delay', 'Flight_price_prediction']

In [8]:
import os

folders = ["Flight_price_prediction", "Flight_delay"]

for folder in folders:
    print(f"\n{'=' * 40}")
    print("FOLDER:", folder)
    print("=" * 40)

    for root, dirs, files in os.walk(folder):
        for file in files:
            print(os.path.join(root, file))

========================================
FOLDER: Flight_price_prediction
========================================
Flight_price_prediction\business.csv
Flight_price_prediction\Clean_Dataset.csv
Flight_price_prediction\economy.csv

========================================
FOLDER: Flight_delay
========================================
Flight_delay\flight_data_2024.csv
Flight_delay\flight_data_2024_data_dictionary.csv
Flight_delay\flight_data_2024_sample.csv

In [9]:
import pandas as pd
import os

# Load the flight price dataset
price_path = os.path.join(
    "Flight_price_prediction", "Clean_Dataset.csv"
)

prices = pd.read_csv(price_path)

print("FLIGHT PRICE DATASET")
print("Shape:", prices.shape)
print("\nColumns:")
print(prices.columns.tolist())

print("\nFirst 5 rows:")
display(prices.head())

FLIGHT PRICE DATASET
Shape: (300153, 12)

Columns:
['Unnamed: 0', 'airline', 'flight', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class', 'duration', 'days_left', 'price']

First 5 rows:

,Unnamed: 0,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

In [10]:
# Load the flight delay dataset
delay_path = os.path.join(
    "Flight_delay", "flight_data_2024.csv"
)

delays = pd.read_csv(delay_path)

print("FLIGHT DELAY DATASET")
print("Shape:", delays.shape)
print("\nColumns:")
print(delays.columns.tolist())

print("\nFirst 5 rows:")
display(delays.head())

FLIGHT DELAY DATASET
Shape: (7079081, 35)

Columns:
['year', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'op_unique_carrier', 'op_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

First 5 rows:

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2024,1,1,1,2024-01-01,9E,4814.0,JFK,"New York, NY",New York,...,0,136.0,122.0,84.0,509.0,0,0,0,0,0
1,2024,1,1,1,2024-01-01,9E,4815.0,MSP,"Minneapolis, MN",Minnesota,...,0,130.0,114.0,88.0,622.0,0,0,0,0,0
2,2024,1,1,1,2024-01-01,9E,4817.0,JFK,"New York, NY",New York,...,0,106.0,90.0,61.0,288.0,0,0,0,0,0
3,2024,1,1,1,2024-01-01,9E,4817.0,RIC,"Richmond, VA",Virginia,...,0,111.0,76.0,51.0,288.0,0,0,0,0,0
4,2024,1,1,1,2024-01-01,9E,4818.0,DTW,"Detroit, MI",Michigan,...,0,79.0,70.0,45.0,237.0,0,0,0,0,0

In [11]:
# Check the flight price dataset
print("FLIGHT PRICE DATA")
print("Rows and columns:", prices.shape)
print("\nColumn names:")
print(prices.columns.tolist())

print("\nMissing values:")
print(prices.isnull().sum().sort_values(ascending=False).head(10))


# Check the flight delay dataset
print("\n\nFLIGHT DELAY DATA")
print("Rows and columns:", delays.shape)
print("\nColumn names:")
print(delays.columns.tolist())

print("\nMissing values:")
print(delays.isnull().sum().sort_values(ascending=False).head(10))

FLIGHT PRICE DATA
Rows and columns: (300153, 12)

Column names:
['Unnamed: 0', 'airline', 'flight', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class', 'duration', 'days_left', 'price']

Missing values:
Unnamed: 0          0
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
dtype: int64


FLIGHT DELAY DATA
Rows and columns: (7079081, 35)

Column names:
['year', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'op_unique_carrier', 'op_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

Missing values:
cancellation_code      6982766
actual_elapsed_time     113814
arr_delay               113814
air_time                113814
wheels_on                97856
taxi_in                  97856
arr_time                 97854
wheels_off               95734
taxi_out                 95734
dep_delay                92970
dtype: int64

In [12]:
import pandas as pd

delay_path = "Flight_delay/flight_data_2024.csv"

# Load a random sample instead of all 7 million rows
delays = pd.read_csv(
    delay_path,
    nrows=200000
)

print("Sample shape:", delays.shape)
print("\nArrival delay summary:")
print(delays["arr_delay"].describe())

print("\nCancelled flights:")
print(delays["cancelled"].value_counts())

print("\nDiverted flights:")
print(delays["diverted"].value_counts())

Sample shape: (200000, 35)

Arrival delay summary:
count    195124.000000
mean          8.260501
std          61.169973
min         -80.000000
25%         -15.000000
50%          -5.000000
75%          12.000000
max        3136.000000
Name: arr_delay, dtype: float64

Cancelled flights:
cancelled
0    195762
1      4238
Name: count, dtype: int64

Diverted flights:
diverted
0    199362
1       638
Name: count, dtype: int64

In [13]:
# Remove cancelled and diverted flights
delay_data = delays[
    (delays["cancelled"] == 0) &
    (delays["diverted"] == 0) &
    (delays["arr_delay"].notna())
].copy()

# Create target: arrival delayed by 15 minutes or more
delay_data["delayed"] = (
    delay_data["arr_delay"] >= 15
).astype(int)

print("Usable flights:", len(delay_data))

print("\nTarget distribution:")
print(delay_data["delayed"].value_counts())

print("\nTarget percentages:")
print(
    (delay_data["delayed"].value_counts(normalize=True) * 100)
    .round(2)
)

Usable flights: 195124

Target distribution:
delayed
0    150999
1     44125
Name: count, dtype: int64

Target percentages:
delayed
0    77.39
1    22.61
Name: proportion, dtype: float64

In [14]:
features = [
    "month",
    "day_of_month",
    "day_of_week",
    "op_unique_carrier",
    "origin",
    "dest",
    "crs_dep_time",
    "crs_arr_time",
    "crs_elapsed_time",
    "distance"
]

X = delay_data[features]
y = delay_data["delayed"]

print("Feature shape:", X.shape)
print("Target shape:", y.shape)

display(X.head())

Feature shape: (195124, 10)
Target shape: (195124,)

,month,day_of_month,day_of_week,op_unique_carrier,origin,dest,crs_dep_time,crs_arr_time,crs_elapsed_time,distance
0,1,1,1,9E,JFK,DTW,1252,1508,136.0,509.0
1,1,1,1,9E,MSP,CLE,1015,1325,130.0,622.0
2,1,1,1,9E,JFK,RIC,1415,1601,106.0,288.0
3,1,1,1,9E,RIC,JFK,1650,1841,111.0,288.0
4,1,1,1,9E,DTW,MKE,1015,1034,79.0,237.0

In [15]:
from sklearn.model_selection import train_test_split

# Identify categorical columns
categorical_features = [
    "op_unique_carrier",
    "origin",
    "dest"
]

# Convert categorical columns to text
for col in categorical_features:
    X[col] = X[col].astype(str)

# Split into training and testing data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Categorical features:", categorical_features)

Training rows: 156099
Testing rows: 39025
Categorical features: ['op_unique_carrier', 'origin', 'dest']

In [16]:
from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=500,
    depth=8,
    learning_rate=0.05,
    loss_function="Logloss",
    eval_metric="AUC",
    verbose=100,
    random_seed=42,
    early_stopping_rounds=50
)

model.fit(
    X_train,
    y_train,
    cat_features=categorical_features,
    eval_set=(X_test, y_test)
)

print("Model training completed!")

0:	test: 0.6855598	best: 0.6855598 (0)	total: 663ms	remaining: 5m 31s
100:	test: 0.7433955	best: 0.7433955 (100)	total: 34.4s	remaining: 2m 16s
200:	test: 0.7553718	best: 0.7553718 (200)	total: 1m 14s	remaining: 1m 50s
300:	test: 0.7614740	best: 0.7614740 (300)	total: 1m 48s	remaining: 1m 11s
400:	test: 0.7646166	best: 0.7646166 (400)	total: 2m 21s	remaining: 34.8s
499:	test: 0.7670169	best: 0.7670169 (499)	total: 2m 50s	remaining: 0us

bestTest = 0.7670168959
bestIteration = 499

Model training completed!

In [17]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    roc_auc_score,
    confusion_matrix
)

predictions = model.predict(X_test)
probabilities = model.predict_proba(X_test)[:, 1]

print("Accuracy:", round(accuracy_score(y_test, predictions), 4))
print("ROC-AUC:", round(roc_auc_score(y_test, probabilities), 4))

print("\nClassification Report:")
print(classification_report(y_test, predictions))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, predictions))

Accuracy: 0.8077
ROC-AUC: 0.767

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.97      0.89     30200
           1       0.71      0.25      0.37      8825

    accuracy                           0.81     39025
   macro avg       0.76      0.61      0.63     39025
weighted avg       0.79      0.81      0.77     39025


Confusion Matrix:
[[29277   923]
 [ 6580  2245]]

In [18]:

from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

for threshold in [0.50, 0.40, 0.35, 0.30, 0.25]:
    predictions_new = (probabilities >= threshold).astype(int)

    print(f"\nThreshold: {threshold}")
    print("Accuracy:", round(accuracy_score(y_test, predictions_new), 3))
    print("Precision:", round(precision_score(y_test, predictions_new, zero_division=0), 3))
    print("Recall:", round(recall_score(y_test, predictions_new), 3))
    print("F1-score:", round(f1_score(y_test, predictions_new), 3))

Threshold: 0.5
Accuracy: 0.808
Precision: 0.709
Recall: 0.254
F1-score: 0.374

Threshold: 0.4
Accuracy: 0.804
Precision: 0.611
Recall: 0.36
F1-score: 0.453

Threshold: 0.35
Accuracy: 0.796
Precision: 0.564
Recall: 0.434
F1-score: 0.491

Threshold: 0.3
Accuracy: 0.778
Precision: 0.509
Recall: 0.518
F1-score: 0.514

Threshold: 0.25
Accuracy: 0.741
Precision: 0.446
Recall: 0.613
F1-score: 0.516

In [21]:
import pandas as pd

price_path = "Flight_price_prediction/Clean_Dataset.csv"

prices = pd.read_csv(price_path)

# Remove the unnecessary index column
prices = prices.drop(columns=["Unnamed: 0"], errors="ignore")

print("Dataset shape:", prices.shape)
print("\nColumns:")
print(prices.columns.tolist())

print("\nFirst 5 rows:")
display(prices.head())

print("\nMissing values:")
print(prices.isnull().sum())

Dataset shape: (300153, 11)

Columns:
['airline', 'flight', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class', 'duration', 'days_left', 'price']

First 5 rows:

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

Missing values:
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [22]:
import pandas as pd

price_path = "Flight_price_prediction/Clean_Dataset.csv"

prices = pd.read_csv(price_path)

# Remove the unnecessary index column
prices = prices.drop(columns=["Unnamed: 0"], errors="ignore")

print("Dataset shape:", prices.shape)
print("\nColumns:")
print(prices.columns.tolist())

print("\nFirst 5 rows:")
display(prices.head())

print("\nMissing values:")
print(prices.isnull().sum())

Dataset shape: (300153, 11)

Columns:
['airline', 'flight', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class', 'duration', 'days_left', 'price']

First 5 rows:

,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price
0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953
1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953
2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956
3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955
4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955

Missing values:
airline             0
flight              0
source_city         0
departure_time      0
stops               0
arrival_time        0
destination_city    0
class               0
duration            0
days_left           0
price               0
dtype: int64

In [23]:
# Select the input features
features = [
    "airline",
    "source_city",
    "departure_time",
    "stops",
    "arrival_time",
    "destination_city",
    "class",
    "duration",
    "days_left"
]

X_price = prices[features]
y_price = prices["price"]

# Identify categorical columns
categorical_price = [
    "airline",
    "source_city",
    "departure_time",
    "stops",
    "arrival_time",
    "destination_city",
    "class"
]

# Convert categorical values to strings
for col in categorical_price:
    X_price[col] = X_price[col].astype(str)

print("Input features shape:", X_price.shape)
print("Target shape:", y_price.shape)
print("\nFeatures:")
print(X_price.columns.tolist())

print("\nSample target prices:")
print(y_price.head())

Input features shape: (300153, 9)
Target shape: (300153,)

Features:
['airline', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class', 'duration', 'days_left']

Sample target prices:
0    5953
1    5953
2    5956
3    5955
4    5955
Name: price, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split

X_price_train, X_price_test, y_price_train, y_price_test = train_test_split(
    X_price,
    y_price,
    test_size=0.2,
    random_state=42
)

print("Training rows:", X_price_train.shape[0])
print("Testing rows:", X_price_test.shape[0])
print("Categorical features:", categorical_price)

Training rows: 240122
Testing rows: 60031
Categorical features: ['airline', 'source_city', 'departure_time', 'stops', 'arrival_time', 'destination_city', 'class']

In [25]:
from catboost import CatBoostRegressor

price_model = CatBoostRegressor(
    iterations=700,
    depth=8,
    learning_rate=0.05,
    loss_function="RMSE",
    verbose=100,
    random_seed=42,
    early_stopping_rounds=50
)

price_model.fit(
    X_price_train,
    y_price_train,
    cat_features=categorical_price,
    eval_set=(X_price_test, y_price_test)
)

print("Flight price model training completed!")

0:	learn: 21648.2921485	test: 21655.3076653	best: 21655.3076653 (0)	total: 339ms	remaining: 3m 57s
100:	learn: 4489.0060820	test: 4551.6806880	best: 4551.6806880 (100)	total: 30.7s	remaining: 3m 1s
200:	learn: 4127.5478327	test: 4192.0585314	best: 4192.0585314 (200)	total: 1m 3s	remaining: 2m 37s
300:	learn: 3945.7174872	test: 4017.3009842	best: 4017.3009842 (300)	total: 1m 38s	remaining: 2m 10s
400:	learn: 3802.7906847	test: 3879.9394817	best: 3879.9394817 (400)	total: 2m 13s	remaining: 1m 39s
500:	learn: 3697.6197633	test: 3779.3362922	best: 3779.3362922 (500)	total: 2m 46s	remaining: 1m 6s
600:	learn: 3605.0757934	test: 3694.6551149	best: 3694.6551149 (600)	total: 3m 27s	remaining: 34.1s
699:	learn: 3530.2334178	test: 3625.2833692	best: 3625.2833692 (699)	total: 4m	remaining: 0us

bestTest = 3625.283369
bestIteration = 699

Flight price model training completed!

In [26]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

price_predictions = price_model.predict(X_price_test)

mae = mean_absolute_error(y_price_test, price_predictions)
rmse = np.sqrt(mean_squared_error(y_price_test, price_predictions))
r2 = r2_score(y_price_test, price_predictions)

print("Flight Price Model Evaluation")
print("------------------------------")
print("MAE:", round(mae, 2))
print("RMSE:", round(rmse, 2))
print("R2 Score:", round(r2, 4))

print("\nActual vs Predicted Prices:")
for i in range(5):
    print(
        "Actual: ₹", y_price_test.iloc[i],
        "| Predicted: ₹", round(price_predictions[i], 2)
    )

Flight Price Model Evaluation
------------------------------
MAE: 2036.3
RMSE: 3625.28
R2 Score: 0.9745

Actual vs Predicted Prices:
Actual: ₹ 7366 | Predicted: ₹ 5985.38
Actual: ₹ 64831 | Predicted: ₹ 70502.61
Actual: ₹ 6195 | Predicted: ₹ 6951.17
Actual: ₹ 60160 | Predicted: ₹ 59822.61
Actual: ₹ 6578 | Predicted: ₹ 6315.89

In [27]:
import os

os.makedirs("models", exist_ok=True)

# Save the flight price model
price_model.save_model("models/flight_price_model.cbm")

# Save the flight delay model
model.save_model("models/flight_delay_model.cbm")

print("Both models saved successfully!")
print("Flight price model: models/flight_price_model.cbm")
print("Flight delay model: models/flight_delay_model.cbm")

Both models saved successfully!
Flight price model: models/flight_price_model.cbm
Flight delay model: models/flight_delay_model.cbm

In [28]:
from catboost import CatBoostRegressor
import pandas as pd

# Load the saved price model
loaded_price_model = CatBoostRegressor()
loaded_price_model.load_model("models/flight_price_model.cbm")

# Example flight details
sample_flight = pd.DataFrame([{
    "airline": "SpiceJet",
    "source_city": "Delhi",
    "departure_time": "Evening",
    "stops": "zero",
    "arrival_time": "Night",
    "destination_city": "Mumbai",
    "class": "Economy",
    "duration": 2.17,
    "days_left": 1
}])

# Predict the ticket price
predicted_price = loaded_price_model.predict(sample_flight)[0]

print("FlightSaver AI - Price Prediction")
print("---------------------------------")
print("Route: Delhi to Mumbai")
print("Airline: SpiceJet")
print("Class: Economy")
print(f"Predicted ticket price: ₹{predicted_price:.2f}")

FlightSaver AI - Price Prediction
---------------------------------
Route: Delhi to Mumbai
Airline: SpiceJet
Class: Economy
Predicted ticket price: ₹8156.06

In [29]:
from catboost import CatBoostClassifier
import pandas as pd

# Load the saved delay model
loaded_delay_model = CatBoostClassifier()
loaded_delay_model.load_model("models/flight_delay_model.cbm")

# Example scheduled flight
sample_delay_flight = pd.DataFrame([{
    "month": 1,
    "day_of_month": 15,
    "day_of_week": 1,
    "op_unique_carrier": "9E",
    "origin": "JFK",
    "dest": "DTW",
    "crs_dep_time": 1252,
    "crs_arr_time": 1508,
    "crs_elapsed_time": 136.0,
    "distance": 509.0
}])

# Ensure categorical columns use strings
for col in ["op_unique_carrier", "origin", "dest"]:
    sample_delay_flight[col] = sample_delay_flight[col].astype(str)

# Predict delay probability
delay_probability = loaded_delay_model.predict_proba(
    sample_delay_flight
)[0][1]

# Use the threshold selected in our experiment
threshold = 0.30
prediction = int(delay_probability >= threshold)

print("FlightSaver AI - Delay Prediction")
print("---------------------------------")
print(f"Delay probability: {delay_probability:.1%}")
print("Prediction:", "Likely delayed" if prediction == 1 else "Likely on time")
print("Delay definition: Arrival at least 15 minutes late")

FlightSaver AI - Delay Prediction
---------------------------------
Delay probability: 11.0%
Prediction: Likely on time
Delay definition: Arrival at least 15 minutes late

In [31]:
from catboost import CatBoostClassifier
import pandas as pd

# Load the saved model
delay_model_test = CatBoostClassifier()
delay_model_test.load_model("models/flight_delay_model.cbm")

# Example flight details
test_flight = pd.DataFrame([{
    "month": 1,
    "day_of_month": 15,
    "day_of_week": 1,
    "op_unique_carrier": "9E",
    "origin": "JFK",
    "dest": "DTW",
    "crs_dep_time": 1252,
    "crs_arr_time": 1508,
    "crs_elapsed_time": 136.0,
    "distance": 509.0
}])

# Keep categorical features as strings
for col in ["op_unique_carrier", "origin", "dest"]:
    test_flight[col] = test_flight[col].astype(str)

# Predict probability
probability = delay_model_test.predict_proba(test_flight)[0][1]

# Use the threshold we tested earlier
threshold = 0.30
result = "Likely delayed" if probability >= threshold else "Likely on time"

print("FlightSaver AI — Delay Prediction")
print("---------------------------------")
print(f"Delay probability: {probability:.2%}")
print(f"Threshold: {threshold:.0%}")
print(f"Prediction: {result}")

FlightSaver AI — Delay Prediction
---------------------------------
Delay probability: 11.01%
Threshold: 30%
Prediction: Likely on time

In [32]:
import json
import os

os.makedirs("models", exist_ok=True)

config = {
    "price_target": "price",
    "price_features": [
        "airline",
        "source_city",
        "departure_time",
        "stops",
        "arrival_time",
        "destination_city",
        "class",
        "duration",
        "days_left"
    ],
    "price_categorical_features": [
        "airline",
        "source_city",
        "departure_time",
        "stops",
        "arrival_time",
        "destination_city",
        "class"
    ],
    "delay_target": "delayed",
    "delay_definition": "Arrival delay of at least 15 minutes",
    "delay_threshold": 0.30,
    "delay_features": [
        "month",
        "day_of_month",
        "day_of_week",
        "op_unique_carrier",
        "origin",
        "dest",
        "crs_dep_time",
        "crs_arr_time",
        "crs_elapsed_time",
        "distance"
    ],
    "delay_categorical_features": [
        "op_unique_carrier",
        "origin",
        "dest"
    ]
}

with open("models/model_config.json", "w") as file:
    json.dump(config, file, indent=4)

print("Model configuration saved successfully!")

Model configuration saved successfully!

In [33]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Baseline: predict the average price from the training data
baseline_price = y_price_train.mean()

baseline_predictions = np.full(
    len(y_price_test),
    baseline_price
)

# Evaluate the baseline
baseline_mae = mean_absolute_error(
    y_price_test, baseline_predictions
)

baseline_rmse = np.sqrt(
    mean_squared_error(y_price_test, baseline_predictions)
)

baseline_r2 = r2_score(
    y_price_test, baseline_predictions
)

# Compare against CatBoost
print("PRICE MODEL COMPARISON")
print("-" * 35)

print("\nAverage-price baseline:")
print("MAE:", round(baseline_mae, 2))
print("RMSE:", round(baseline_rmse, 2))
print("R2:", round(baseline_r2, 4))

print("\nCatBoost model:")
print("MAE:", round(mean_absolute_error(y_price_test, price_predictions), 2))
print("RMSE:", round(np.sqrt(mean_squared_error(y_price_test, price_predictions)), 2))
print("R2:", round(r2_score(y_price_test, price_predictions), 4))

PRICE MODEL COMPARISON
-----------------------------------

Average-price baseline:
MAE: 19768.69
RMSE: 22704.24
R2: -0.0

CatBoost model:
MAE: 2036.3
RMSE: 3625.28
R2: 0.9745

In [34]:
import pandas as pd
import numpy as np

error_check = pd.DataFrame({
    "actual_price": y_price_test.to_numpy(),
    "predicted_price": price_predictions
})

error_check["absolute_error"] = abs(
    error_check["actual_price"] - error_check["predicted_price"]
)

# Group tickets by actual price
error_check["price_range"] = pd.cut(
    error_check["actual_price"],
    bins=[0, 10000, 25000, 50000, float("inf")],
    labels=["Below ₹10,000", "₹10,000–25,000",
            "₹25,000–50,000", "Above ₹50,000"]
)

summary = error_check.groupby(
    "price_range", observed=False
).agg(
    ticket_count=("actual_price", "count"),
    average_actual_price=("actual_price", "mean"),
    average_absolute_error=("absolute_error", "mean")
).round(2)

print(summary)

                ticket_count  average_actual_price  average_absolute_error
price_range
Below ₹10,000          34769               5247.53                  855.91
₹10,000–25,000          7206              14220.94                 2165.28
₹25,000–50,000          6217              41659.90                 4204.89
Above ₹50,000          11839              60001.81                 4285.59

In [35]:
# Check for duplicate rows in the flight price dataset

duplicate_count = prices.duplicated().sum()

print("Total records:", len(prices))
print("Duplicate records:", duplicate_count)
print(
    "Duplicate percentage:",
    round((duplicate_count / len(prices)) * 100, 2),
    "%"
)

Total records: 300153
Duplicate records: 0
Duplicate percentage: 0.0 %

In [36]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": features,
    "Importance": price_model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print(importance.to_string(index=False))

         Feature  Importance
           class   87.052144
        duration    4.907504
         airline    2.048320
     source_city    1.772275
destination_city    1.644964
       days_left    1.023230
    arrival_time    0.641808
           stops    0.471809
  departure_time    0.437945

In [37]:
import os

os.makedirs("results", exist_ok=True)

importance.to_csv(
    "results/price_feature_importance.csv",
    index=False
)

print("Feature importance report saved successfully!")

Feature importance report saved successfully!

In [38]:
import pandas as pd
import os

delay_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.feature_importances_
})

delay_importance = delay_importance.sort_values(
    by="Importance",
    ascending=False
)

print(delay_importance.to_string(index=False))

os.makedirs("results", exist_ok=True)
delay_importance.to_csv(
    "results/delay_feature_importance.csv",
    index=False
)

print("\nDelay feature importance report saved successfully!")

          Feature  Importance
     day_of_month   22.033134
      day_of_week   14.835614
op_unique_carrier   14.796545
           origin   13.883616
             dest   10.802134
     crs_dep_time    9.964990
     crs_arr_time    6.249356
 crs_elapsed_time    4.093631
         distance    3.340979
            month    0.000000

Delay feature importance report saved successfully!

In [39]:
import os

files_to_check = [
    "models/flight_price_model.cbm",
    "models/flight_delay_model.cbm",
    "models/model_config.json",
    "results/price_feature_importance.csv",
    "results/delay_feature_importance.csv"
]

for file in files_to_check:
    if os.path.exists(file):
        print(f"FOUND: {file}")
    else:
        print(f"MISSING: {file}")

FOUND: models/flight_price_model.cbm
FOUND: models/flight_delay_model.cbm
FOUND: models/model_config.json
FOUND: results/price_feature_importance.csv
FOUND: results/delay_feature_importance.csv

In [40]:
from catboost import CatBoostRegressor, CatBoostClassifier

# Load the saved price model
saved_price_model = CatBoostRegressor()
saved_price_model.load_model("models/flight_price_model.cbm")

# Load the saved delay model
saved_delay_model = CatBoostClassifier()
saved_delay_model.load_model("models/flight_delay_model.cbm")

print("Price model loaded successfully!")
print("Delay model loaded successfully!")
print("\nBoth saved models are ready to use.")

Price model loaded successfully!
Delay model loaded successfully!

Both saved models are ready to use.

In [42]:
import pandas as pd

sample_flight = pd.DataFrame([{
    "airline": "SpiceJet",
    "source_city": "Delhi",
    "departure_time": "Evening",
    "stops": "zero",
    "arrival_time": "Night",
    "destination_city": "Mumbai",
    "class": "Economy",
    "duration": 2.17,
    "days_left": 1
}])

predicted_price = saved_price_model.predict(sample_flight)[0]

print("FlightSaver AI - Price Prediction")
print(f"Predicted ticket price: ₹{predicted_price:,.2f}")

FlightSaver AI - Price Prediction
Predicted ticket price: ₹8,156.06

In [43]:
import pandas as pd

sample_delay_flight = pd.DataFrame([{
    "month": 1,
    "day_of_month": 15,
    "day_of_week": 1,
    "op_unique_carrier": "9E",
    "origin": "JFK",
    "dest": "DTW",
    "crs_dep_time": 1252,
    "crs_arr_time": 1508,
    "crs_elapsed_time": 136.0,
    "distance": 509.0
}])

delay_probability = saved_delay_model.predict_proba(
    sample_delay_flight
)[0][1]

threshold = 0.30

prediction = (
    "Likely delayed"
    if delay_probability >= threshold
    else "Likely on time"
)

print("FlightSaver AI - Delay Prediction")
print(f"Delay probability: {delay_probability:.2%}")
print(f"Decision threshold: {threshold:.0%}")
print(f"Prediction: {prediction}")

FlightSaver AI - Delay Prediction
Delay probability: 11.01%
Decision threshold: 30%
Prediction: Likely on time

In [44]:
print("Earliest flight date:")
print(delays["fl_date"].min())

print("\nLatest flight date:")
print(delays["fl_date"].max())

print("\nUnique flight dates:")
print(delays["fl_date"].nunique())

Earliest flight date:
2024-01-01

Latest flight date:
2024-01-12

Unique flight dates:
12

In [45]:
import pandas as pd

date_check = pd.read_csv(
    "Flight_delay/flight_data_2024.csv",
    usecols=["fl_date"]
)

date_check["fl_date"] = pd.to_datetime(
    date_check["fl_date"],
    errors="coerce"
)

print("Full dataset earliest date:", date_check["fl_date"].min())
print("Full dataset latest date:", date_check["fl_date"].max())
print("Unique flight dates:", date_check["fl_date"].nunique())

print("\nFlights per month:")
print(date_check["fl_date"].dt.month.value_counts().sort_index())

Full dataset earliest date: 2024-01-01 00:00:00
Full dataset latest date: 2024-12-31 00:00:00
Unique flight dates: 366

Flights per month:
fl_date
1     547271
2     519221
3     591767
4     582205
5     609743
6     611132
7     634613
8     619025
9     582622
10    615497
11    575404
12    590581
Name: count, dtype: int64

In [46]:
import pandas as pd
import os

input_path = "Flight_delay/flight_data_2024.csv"
sample_path = "Flight_delay/flight_data_2024_random_sample.csv"

sample_size = 20000
chunk_size = 200000
random_seed = 42

sample_chunks = []

for chunk in pd.read_csv(input_path, chunksize=chunk_size):
    chunk_sample = chunk.sample(
        n=min(sample_size, len(chunk)),
        random_state=random_seed
    )
    sample_chunks.append(chunk_sample)

random_sample = pd.concat(sample_chunks, ignore_index=True)

random_sample.to_csv(sample_path, index=False)

print("Random sample created successfully!")
print("Sample rows:", len(random_sample))
print("Date range:", random_sample["fl_date"].min(), "to",
      random_sample["fl_date"].max())
print("Unique dates:", random_sample["fl_date"].nunique())
print("Saved to:", sample_path)

C:\Users\sanga\AppData\Local\Temp\ipykernel_31816\374896812.py:13: DtypeWarning: Columns (24: cancellation_code) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv(input_path, chunksize=chunk_size):

Random sample created successfully!
Sample rows: 720000
Date range: 2024-01-01 to 2024-12-31
Unique dates: 366
Saved to: Flight_delay/flight_data_2024_random_sample.csv

In [47]:
import pandas as pd

sample_path = "Flight_delay/flight_data_2024_random_sample.csv"

delay_sample = pd.read_csv(sample_path)

usable_sample = delay_sample[
    (delay_sample["cancelled"] == 0) &
    (delay_sample["diverted"] == 0) &
    (delay_sample["arr_delay"].notna())
].copy()

usable_sample["delayed"] = (
    usable_sample["arr_delay"] >= 15
).astype(int)

print("Total sampled flights:", len(delay_sample))
print("Usable flights:", len(usable_sample))
print("\nDelay classification:")
print(usable_sample["delayed"].value_counts())
print("\nDelay percentages:")
print(
    (usable_sample["delayed"].value_counts(normalize=True) * 100)
    .round(2)
)

Total sampled flights: 720000
Usable flights: 708459

Delay classification:
delayed
0    559860
1    148599
Name: count, dtype: int64

Delay percentages:
delayed
0    79.03
1    20.97
Name: proportion, dtype: float64

In [48]:
import pandas as pd
from sklearn.model_selection import train_test_split

delay_data = usable_sample.copy()

features = [
    "month",
    "day_of_month",
    "day_of_week",
    "op_unique_carrier",
    "origin",
    "dest",
    "crs_dep_time",
    "crs_arr_time",
    "crs_elapsed_time",
    "distance"
]

categorical_features = [
    "op_unique_carrier",
    "origin",
    "dest"
]

X = delay_data[features].copy()
y = delay_data["delayed"].copy()

for col in categorical_features:
    X[col] = X[col].astype(str)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training rows:", len(X_train))
print("Testing rows:", len(X_test))
print("Training delay rate:", round(y_train.mean() * 100, 2), "%")
print("Testing delay rate:", round(y_test.mean() * 100, 2), "%")
print("Features prepared successfully!")

Training rows: 566767
Testing rows: 141692
Training delay rate: 20.97 %
Testing delay rate: 20.98 %
Features prepared successfully!

In [49]:
from catboost import CatBoostClassifier

improved_delay_model = CatBoostClassifier(
    iterations=700,
    depth=8,
    learning_rate=0.05,
    loss_function="Logloss",
    eval_metric="AUC",
    verbose=100,
    random_seed=42,
    early_stopping_rounds=50
)

improved_delay_model.fit(
    X_train,
    y_train,
    cat_features=categorical_features,
    eval_set=(X_test, y_test)
)

print("\nImproved delay model training complete!")

0:	test: 0.6457513	best: 0.6457513 (0)	total: 613ms	remaining: 7m 8s
100:	test: 0.6880250	best: 0.6880250 (100)	total: 1m	remaining: 5m 58s
200:	test: 0.6981279	best: 0.6981279 (200)	total: 2m 3s	remaining: 5m 6s
300:	test: 0.7039142	best: 0.7039142 (300)	total: 3m 12s	remaining: 4m 15s
400:	test: 0.7080830	best: 0.7080830 (400)	total: 4m 22s	remaining: 3m 15s
500:	test: 0.7107057	best: 0.7107057 (500)	total: 5m 29s	remaining: 2m 10s
600:	test: 0.7125832	best: 0.7125832 (600)	total: 6m 34s	remaining: 1m 5s
699:	test: 0.7138900	best: 0.7138900 (699)	total: 7m 49s	remaining: 0us

bestTest = 0.7138899631
bestIteration = 699


Improved delay model training complete!

In [50]:
from catboost import CatBoostClassifier

improved_delay_model = CatBoostClassifier(
    iterations=700,
    depth=8,
    learning_rate=0.05,
    loss_function="Logloss",
    eval_metric="AUC",
    verbose=100,
    random_seed=42,
    early_stopping_rounds=50
)

improved_delay_model.fit(
    X_train,
    y_train,
    cat_features=categorical_features,
    eval_set=(X_test, y_test)
)

print("\nImproved delay model training complete!")

0:	test: 0.6457513	best: 0.6457513 (0)	total: 694ms	remaining: 8m 4s
100:	test: 0.6880250	best: 0.6880250 (100)	total: 1m 5s	remaining: 6m 29s
200:	test: 0.6981279	best: 0.6981279 (200)	total: 2m 10s	remaining: 5m 24s
300:	test: 0.7039142	best: 0.7039142 (300)	total: 3m 19s	remaining: 4m 24s
400:	test: 0.7080830	best: 0.7080830 (400)	total: 4m 31s	remaining: 3m 23s
500:	test: 0.7107057	best: 0.7107057 (500)	total: 5m 44s	remaining: 2m 17s
600:	test: 0.7125832	best: 0.7125832 (600)	total: 6m 49s	remaining: 1m 7s
699:	test: 0.7138900	best: 0.7138900 (699)	total: 7m 52s	remaining: 0us

bestTest = 0.7138899631
bestIteration = 699


Improved delay model training complete!

In [51]:
from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    classification_report,
    confusion_matrix,
    f1_score
)

# Predict delay probabilities
improved_probabilities = improved_delay_model.predict_proba(X_test)[:, 1]

# Use the same 30% threshold as before
threshold = 0.30
improved_predictions = (
    improved_probabilities >= threshold
).astype(int)

print("Improved Delay Model Evaluation")
print("--------------------------------")
print("Accuracy:", round(
    accuracy_score(y_test, improved_predictions), 4
))
print("ROC-AUC:", round(
    roc_auc_score(y_test, improved_probabilities), 4
))
print("F1-score:", round(
    f1_score(y_test, improved_predictions), 4
))

print("\nClassification Report:")
print(classification_report(y_test, improved_predictions))

print("Confusion Matrix:")
print(confusion_matrix(y_test, improved_predictions))

Improved Delay Model Evaluation
--------------------------------
Accuracy: 0.7627
ROC-AUC: 0.7139
F1-score: 0.4205

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.86      0.85    111972
           1       0.43      0.41      0.42     29720

    accuracy                           0.76    141692
   macro avg       0.64      0.63      0.64    141692
weighted avg       0.76      0.76      0.76    141692

Confusion Matrix:
[[95879 16093]
 [17524 12196]]

In [52]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

# Original model: evaluate on its original test set
original_probabilities = model.predict_proba(
    X_test if False else X_test
)[:, 1]

In [53]:
from sklearn.metrics import precision_score, recall_score, f1_score

print("Threshold | Precision | Recall | F1-score")

for threshold in [0.20, 0.25, 0.30, 0.35, 0.40, 0.50]:
    predictions = (improved_probabilities >= threshold).astype(int)

    print(
        f"{threshold:8.2f} | "
        f"{precision_score(y_test, predictions):9.3f} | "
        f"{recall_score(y_test, predictions):6.3f} | "
        f"{f1_score(y_test, predictions):8.3f}"
    )

Threshold | Precision | Recall | F1-score
    0.20 |     0.332 |  0.667 |    0.444
    0.25 |     0.382 |  0.528 |    0.443
    0.30 |     0.431 |  0.410 |    0.420
    0.35 |     0.475 |  0.310 |    0.375
    0.40 |     0.519 |  0.229 |    0.318
    0.50 |     0.616 |  0.103 |    0.177

In [54]:
import json
import os

os.makedirs("models", exist_ok=True)

improved_delay_model.save_model(
    "models/flight_delay_model_full_year.cbm"
)

config_path = "models/model_config.json"

with open(config_path, "r") as file:
    config = json.load(file)

config["delay_threshold"] = 0.20
config["delay_model_file"] = "flight_delay_model_full_year.cbm"

with open(config_path, "w") as file:
    json.dump(config, file, indent=4)

print("Full-year delay model saved!")
print("Selected threshold: 0.20")
print("Original delay model preserved.")

Full-year delay model saved!
Selected threshold: 0.20
Original delay model preserved.

In [55]:
import json
from catboost import CatBoostClassifier

with open("models/model_config.json", "r") as file:
    config = json.load(file)

final_delay_model = CatBoostClassifier()
final_delay_model.load_model(
    "models/" + config["delay_model_file"]
)

threshold = config["delay_threshold"]

probability = final_delay_model.predict_proba(
    sample_delay_flight
)[0][1]

prediction = "Likely delayed" if probability >= threshold else "Likely on time"

print("FlightSaver AI - Final Verification")
print("Saved model loaded successfully!")
print(f"Configured threshold: {threshold:.0%}")
print(f"Delay probability: {probability:.2%}")
print(f"Prediction: {prediction}")
print("\nModel integration check passed!")

FlightSaver AI - Final Verification
Saved model loaded successfully!
Configured threshold: 20%
Delay probability: 40.03%
Prediction: Likely delayed

Model integration check passed!